diff --git a/Makefile b/Makefile
index 20240ce..ee6f70c 100644
--- a/Makefile
+++ b/Makefile
@@ -1,6 +1,6 @@
 VERSION = 2.3
-CC = $(CROSS_COMPILE)gcc
-AR = $(CROSS_COMPILE)ar
+#CC = $(CROSS_COMPILE)gcc
+#AR = $(CROSS_COMPILE)ar
 
 OBJDIR = bld
 
